platform: Any CPU
configuration: Release

before_build:
- cmd: nuget restore Source/SharpGeometry.sln
build:
  project: Source/SharpGeometry.sln
  verbosity: minimal

after_test: 
  - Scripts/OpenCover.bat
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "OpenCover/Coverage.xml"